<a href="https://colab.research.google.com/github/mukkatharun/DimensionalityReductionTechniques/blob/main/DimensionalityReductionTechniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
! pip install kaggle
! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json
! kaggle datasets download CooperUnion/cardataset
! unzip cardataset.zip

mkdir: cannot create directory ‘/root/.kaggle’: File exists
  0% 0.00/103k [00:00<?, ?B/s]
100% 103k/103k [00:00<00:00, 39.2MB/s]
Archive:  cardataset.zip
  inflating: data.csv                


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import numpy as cov

In [4]:
data = pd.read_csv('data.csv')
data.head()

<bound method NDFrame.head of           Make       Model  Year  ... city mpg  Popularity   MSRP
0          BMW  1 Series M  2011  ...       19        3916  46135
1          BMW    1 Series  2011  ...       19        3916  40650
2          BMW    1 Series  2011  ...       20        3916  36350
3          BMW    1 Series  2011  ...       18        3916  29450
4          BMW    1 Series  2011  ...       18        3916  34500
...        ...         ...   ...  ...      ...         ...    ...
11909    Acura         ZDX  2012  ...       16         204  46120
11910    Acura         ZDX  2012  ...       16         204  56670
11911    Acura         ZDX  2012  ...       16         204  50620
11912    Acura         ZDX  2013  ...       16         204  50920
11913  Lincoln      Zephyr  2006  ...       17          61  28995

[11914 rows x 16 columns]>

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

In [6]:

data = data.drop(["Number of Doors", "Market Category", "Vehicle Style", "Model", "Popularity"], axis=1)
data.shape

(11914, 11)

In [8]:
data.isna().sum()

Make                  0
Year                  0
Engine Fuel Type      3
Engine HP            69
Engine Cylinders     30
Transmission Type     0
Driven_Wheels         0
Vehicle Size          0
highway MPG           0
city mpg              0
MSRP                  0
dtype: int64

In [11]:
data = data.dropna()

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11813 entries, 0 to 11913
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11813 non-null  object 
 1   Year               11813 non-null  int64  
 2   Engine Fuel Type   11813 non-null  object 
 3   Engine HP          11813 non-null  float64
 4   Engine Cylinders   11813 non-null  float64
 5   Transmission Type  11813 non-null  object 
 6   Driven_Wheels      11813 non-null  object 
 7   Vehicle Size       11813 non-null  object 
 8   highway MPG        11813 non-null  int64  
 9   city mpg           11813 non-null  int64  
 10  MSRP               11813 non-null  int64  
dtypes: float64(2), int64(4), object(5)
memory usage: 1.1+ MB


In [19]:
data = data[data['highway MPG'] < 330]
pcaData = data[['Engine HP', 'Engine Cylinders', 'highway MPG', 'city mpg']]

In [20]:
pcaData

Engine HP  Engine Cylinders  highway MPG  city mpg
0          335.0               6.0           26        19
1          300.0               6.0           28        19
2          300.0               6.0           28        20
3          230.0               6.0           28        18
4          230.0               6.0           28        18
...          ...               ...          ...       ...
11909      300.0               6.0           23        16
11910      300.0               6.0           23        16
11911      300.0               6.0           23        16
11912      300.0               6.0           23        16
11913      221.0               6.0           26        17

[11812 rows x 4 columns]

In [21]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# transform data
scaled = scaler.fit_transform(pcaData)
scaled

array([[ 0.78215259,  0.19965895, -0.04295239, -0.05009989],
       [ 0.4618298 ,  0.19965895,  0.25091015, -0.05009989],
       [ 0.4618298 ,  0.19965895,  0.25091015,  0.1030919 ],
       ...,
       [ 0.4618298 ,  0.19965895, -0.48374621, -0.50967523],
       [ 0.4618298 ,  0.19965895, -0.48374621, -0.50967523],
       [-0.26118448,  0.19965895, -0.04295239, -0.35648345]])

In [44]:
from sklearn.decomposition import PCA
pca = PCA(1)
# fit on data
pca.fit(scaled)
pca.fit_transform(scaled)

array([[-0.4992832 ],
       [-0.20438234],
       [-0.12560081],
       ...,
       [-0.82193168],
       [-0.82193168],
       [-0.19296736]])

In [45]:
# pca.fit(scaled)
print(pca.components_)
print(pca.explained_variance_)

[[-0.44461078 -0.51827122  0.51888849  0.51426738]]
[2.97791837]


In [47]:
principalComponents = pca.transform(scaled)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1'])
principalDf['principal component 1']

0       -0.499283
1       -0.204382
2       -0.125601
3        0.001674
4        0.001674
           ...   
11807   -0.821932
11808   -0.821932
11809   -0.821932
11810   -0.821932
11811   -0.192967
Name: principal component 1, Length: 11812, dtype: float64